import type {ReactNode} from 'react';
import clsx from 'clsx';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import Layout from '@theme/Layout';
import HomepageFeatures from '@site/src/components/HomepageFeatures';
import Heading from '@theme/Heading';

import styles from './index.module.css';

function HomepageHeader() {
  const {siteConfig} = useDocusaurusContext();
  return (
    <header className={clsx('hero hero--primary', styles.heroBanner)}>
      <div className="container">
        <Heading as="h1" className="hero__title">
          Build AI-Powered Data Pipelines with Simple Configuration
        </Heading>
        <p className="hero__subtitle">
          Transform complex data processing workflows into YAML files. Connect APIs, process data, 
          and integrate AI models—all without writing code.
        </p>
        <div className={styles.buttons}>
          <Link
            className="button button--secondary button--lg"
            to="/docs/getting-started/quick-start">
            Get Started in 5 Minutes 🚀
          </Link>
          <Link
            className="button button--outline button--lg margin-left--md"
            to="/docs/examples">
            View Examples
          </Link>
        </div>
        <div className={styles.quickPreview}>
          <pre className={styles.codePreview}>
{`# Transform any data into AI insights
data_sources:
  sales_data:
    type: csv
    path: quarterly_sales.csv
  market_trends:
    type: rest
    url: https://api.trends.com/data

processing:
  contextual_filtering:
    sales_data:
      - field: revenue
        condition: "revenue > avg(revenue) * 1.5"

ai_interface:
  prompts:
    strategic_analysis: |
      Analyze this data and provide strategic recommendations:
      {{sales_data}} {{market_trends}}

output:
  type: file
  path: strategic_insights.md`}
          </pre>
        </div>
      </div>
    </header>
  );
}

function SocialProofSection(): ReactNode {
  return (
    <section className={styles.socialProof}>
      <div className="container">
        <div className="row">
          <div className="col col--12 text--center">
            <h2>Join the Growing Community</h2>
            <div className={styles.statsGrid}>
              <div className={styles.statItem}>
                <h3>⭐ GitHub Stars</h3>
                <p>Growing open source community</p>
              </div>
              <div className={styles.statItem}>
                <h3>📦 PyPI Downloads</h3>
                <p>Production-ready framework</p>
              </div>
              <div className={styles.statItem}>
                <h3>🏢 Enterprise Ready</h3>
                <p>Built for production workloads</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function ClaudeCodeSection(): ReactNode {
  return (
    <section className={styles.claudeCode}>
      <div className="container">
        <div className="row">
          <div className="col col--12 text--center">
            <h2>🤖 Works Seamlessly with Claude Code</h2>
            <p className={styles.claudeSubtitle}>
              The only AI data framework that <strong>writes configurations for you</strong>
            </p>
            <div className={styles.claudeDemo}>
              <div className={styles.claudeStep}>
                <h3>1. Just Tell Claude What You Want</h3>
                <div className={styles.chatBubble}>
                  "Analyze my customer CSV and create a pipeline that filters active users over 25, 
                  then generates AI insights about their behavior patterns"
                </div>
              </div>
              <div className={styles.arrow}>→</div>
              <div className={styles.claudeStep}>
                <h3>2. Claude Introspects Your Data</h3>
                <div className={styles.introspectionBox}>
                  <strong>Automatically detects:</strong>
                  <ul>
                    <li>✅ Schema & data types</li>
                    <li>✅ Sample data & patterns</li>
                    <li>✅ Relationships between sources</li>
                    <li>✅ Optimal operations to use</li>
                  </ul>
                </div>
              </div>
              <div className={styles.arrow}>→</div>
              <div className={styles.claudeStep}>
                <h3>3. Complete Config Generated</h3>
                <div className={styles.generatedConfig}>
                  <pre>{`# Generated by Claude Code
data_sources:
  customers:
    type: csv
    path: customers.csv
processing:
  contextual_filtering:
    customers:
      - field: age
        condition: "age > 25 && status == 'active'"
ai_interface:
  prompts:
    behavior_analysis:
      system: "You are a customer behavior analyst"
      user_template: "Analyze patterns in: {{customers}}"
output:
  type: file
  path: customer_insights.json`}</pre>
                </div>
              </div>
            </div>
            <div className={styles.claudeFeatures}>
              <div className={styles.feature}>
                <h4>🔍 Smart Data Introspection</h4>
                <p>Claude analyzes your data sources and understands structure, types, and relationships automatically</p>
              </div>
              <div className={styles.feature}>
                <h4>⚡ Instant Configuration</h4>
                <p>From idea to working pipeline in seconds. No manual YAML writing or data exploration needed</p>
              </div>
              <div className={styles.feature}>
                <h4>🧠 Intelligent Recommendations</h4>
                <p>Claude suggests optimal operations, filters, and AI prompts based on your data patterns</p>
              </div>
            </div>
            <div className={styles.claudeCta}>
              <Link
                className="button button--primary button--lg"
                to="/docs/claude-code-integration">
                Try with Claude Code Now
              </Link>
              <p className={styles.claudeNote}>
                💡 <strong>Pro tip:</strong> Use Claude Code to build complex pipelines without learning YAML syntax
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function GetStartedSection(): ReactNode {
  return (
    <section className={styles.getStarted}>
      <div className="container">
        <div className="row">
          <div className="col col--12 text--center">
            <h2>Get Started in 3 Steps</h2>
            <div className={styles.stepsGrid}>
              <div className={styles.step}>
                <div className={styles.stepNumber}>1</div>
                <h3>Install</h3>
                <code>pip install shedboxai</code>
              </div>
              <div className={styles.step}>
                <div className={styles.stepNumber}>2</div>
                <h3>Configure</h3>
                <code>Create config.yaml</code>
              </div>
              <div className={styles.step}>
                <div className={styles.stepNumber}>3</div>
                <h3>Run</h3>
                <code>shedboxai run config.yaml</code>
              </div>
            </div>
            <div className={styles.finalCta}>
              <Link
                className="button button--primary button--lg"
                to="/docs/getting-started/installation">
                Start Building Now
              </Link>
              <Link
                className="button button--outline button--lg margin-left--md"
                to="https://github.com/shedboxai/shedboxai">
                ⭐ Star on GitHub
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default function Home(): ReactNode {
  const {siteConfig} = useDocusaurusContext();
  return (
    <Layout
      title={`${siteConfig.title} - AI-powered data processing framework`}
      description="Lightweight framework for building AI-powered data processing pipelines through simple YAML configuration">
      <HomepageHeader />
      <main>
        <HomepageFeatures />
        <ClaudeCodeSection />
        <SocialProofSection />
        <GetStartedSection />
      </main>
    </Layout>
  );
}
